server:
  port: 8000
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
  tomcat:
    uri-encoding: UTF-8
spring:
#  security:
#    user:
#      name: test
#      password: 1234
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 915164523287-kacli0crnvu7bqq3s4adlent6dk7joit.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          naver:
            client-id: Zwse3ymINvctDEC0ok7p
            client-secret: 0gfRhdmK3Q
            scope:
            - email
            - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  mvc:
    static-path-pattern:  /static/**
  datasource:
    driver-class-name:  org.mariadb.jdbc.Driver                                           
    url: jdbc:mariadb://web-study-0223.cb8c0c6206ug.ap-northeast-2.rds.amazonaws.com:3306/study?useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: 46tkfkdgo!Q
    
mybatis:
  mapper-locations:
  - /mappers/*.xml